name: COVID_CH
setup: data/ch/geodata.csv
parameters: data/parameters.yaml
timewindow_R0:
  left: ["2020-03-01", "2020-03-10"]
  right: ["2020-03-29", "2020-04-05"]
likelihoods:
  to_compute:
    - d-deltah
    - c-d-deltah
   # - d
  to_plot:
     - d-deltah
tvary: "2020-03-08"
sdfrac: 0.3
parameters_to_fit:
#  pi2h:
#    upper: .8
#    lower: .2
#    transform: "logit"
places:
  - CH
#  - BE
#  - BL
#  - BS
#  - FR
#  - GE
#  - GR
#  - JU
  #- LU
#  - NE
#  - TI
#  - VD
#  - VS
#  - ZH
