name: COVID_CH
setup: data/ch/geodata.csv
parameters: data/parameters_v3.yaml
data_path: data/ch/cases/covid_19/fallzahlen_kanton_total_csv_v2
model: pomp_skeleton_v4.R
timewindow_R0:
  left: ["2020-03-01", "2020-03-10"]
  right: ["2020-03-29", "2020-04-05"]
likelihoods:
  to_compute:
    - d-deltah
  to_plot:
     - d-deltah
tvary: "2020-03-05"
sdfrac: .3
parameters_to_fit:
  R0_0:
    upper: 3
    lower: 1.5
    transform: log
    rw_sd: ivp
  I_0:
    upper: 50
    lower: 1
    transform: logit
    rw_sd: ivp
  id2o:
    upper: 10
    lower: 5
    transform: log
    rw_sd: regular
profile_bounds:
  R0_0:
    upper: 4.5
    lower: 1.5
places:
  - CH
  - BE
  - BL
  - BS
  - FR
  - GE
  - GR
  - JU
#  - LU
  - NE
  - TI
  - UR
  - VD
  - VS
  - ZH
