name: COVID_CH
setup: data/ch/geodata.csv
parameters: data/parameters_v2.yaml
timewindow_R0:
  left: ["2020-03-01", "2020-03-10"]
  right: ["2020-03-29", "2020-04-05"]
likelihoods:
  to_compute:
    - d-deltah
  #  - c-d-deltah
   # - d
  to_plot:
     - d-deltah
tvary: "2020-02-28"
sdfrac: 0.3
parameters_to_fit:
  id2o:
    upper: 36.5
    lower: 18
    transform: "log"
places:
  - CH
  - BE
  - BL
  - BS
  - FR
  - GE
  - GR
  - JU
#  - LU
  - NE
  - TI
  - UR
  - VD
  - VS
  - ZH
