name: CH
start_date: 2020-01-31
end_date: 2020-10-01
nsimulations: 10000
dt: 0.25
report_location_name: Switzerland

spatial_setup:
  base_path: ../data/ch
  setup_name: CH
  geodata: geodata.csv
  shapefile_name: shp/ch.shp
  shapefile: shp/ch.shp # Two is redundant.  We should fix this
  #mobility: mobility.txt
  mobility: mobility_matrix_adj.csv
  popnodes: pop2018
  nodenames: ShortName  # Name of the column in geodata with uniquely name of nodes
  include_in_report: CH

#seeding:
#  method: FolderDraw
#  folder_path: model_output/importation/

seeding:
  method: PoissonDistributed
  lambda_file: ../data/ch/seeding.csv

interventions:
  scenarios:
    - Stopped
#    - TestIsolate2
#    - TestIsolate1
    - R0-1dot2
    - R0-0dot9
  settings:
    Current:
      template: ReduceR0
      period_start_date: 2020-01-31
      period_end_date: 2020-03-13   
      value:
        distribution: fixed
        value: 0
    Stopped:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0
    R0-1dot2:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0
    R0-0dot9:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0
    TestIsolate1:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0
    TestIsolate2:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0

seir:
  parameters:
    sigma: 1 / 4.2
    gamma:
      #distribution: uniform
      #low: 1 / 6
      #high: 1 / 2.6
      distribution: uniform
      low: 1 / 3
      high: 1 / 1.5
    R0s:
      distribution: uniform
      low: 2
      high: 3

hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    #time_hosp: [1.23, 0.79]
    #time_disch: [log(11.5), log(1.22)]
    #time_death: [log(11.25), log(1.15)]
    #time_ICU: [log(8.25), log(2.2)]
    #time_ICUdur: [log(16), log(2.96)]
    #time_vent: [log(10.5), log((10.5-8)/1.35)]
    # OUR FIRST PARAMETERS
    #time_vent: [log(10.5), log((10.5-8)/1.35)]
    #time_hosp: [1.23, 0.79]
    #time_disch: [1.75, 0.82]
    #time_death: [1.75, 0.82]
    #time_ICU: [0.11, 0.98]
    #time_ICUdur: [1.62, 0.96]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    time_hosp: [1.23, 0.79]
    time_disch: [1.549637396328431, 0.6704312837818938]
    #time_disch: [2.049637396328431,  0.3704312837818938]
    time_death: [1.893025597681255, 0.911666106028342]
    time_ICU: [0.09803726763057043, 0.9766455722082084]
    time_ICUdur: [1.8317363228784524, 0.9766455722082084]
    p_death: [.0025, .005, .01]
    p_death_names: ["low","med","high"]
    p_death_rate: 0.11
    p_ICU: 0.20
    p_vent: 0.0

report:
  data_settings:
    pop_year: 2018
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: ["CC","CS", "TI"]
    scenario_labels:
      - Stopped
      #- Test & Isolate (35-30)
      #- Test & Isolate (50-60)
      - R0 around 1.2
      - R0 around 0.9
    scenario_colors: ["#D95F02", "#1B9E77", "#0000A0"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
    display_dates: ["2020-5-15", "2020-6-15", "2020-9-15"]
  filtering:
    do_filtering: TRUE
    var_to_filter: ["NincidDeath", "NhospCurr"]
    data_path: reports/national_data.csv 
    dist: ["pois", "pois"]
    replace_zero: [TRUE, TRUE] 
    under_reporting: [1, 1]
    
