name: CH
start_date: 2020-01-31
end_date: 2020-10-01
nsimulations: 100
dt: 0.25
report_location_name: Switzerland

spatial_setup:
  base_path: ../data/ch
  setup_name: CH
  geodata: geodata.csv
  shapefile_name: shp/ch.shp
  shapefile: shp/ch.shp # Two is redundant.  We should fix this
  mobility: mobility.txt
  popnodes: pop2018
  nodenames: ShortName  # Name of the column in geodata with uniquely name of nodes
  include_in_report: CH

#seeding:
#  method: FolderDraw
#  folder_path: model_output/importation/

seeding:
  method: PoissonDistributed
  lambda_file: ../data/ch/seeding.csv

interventions:
  scenarios:
    - Current
    - Stopped
    - TestIsolate
  settings:
    Current:
      template: ReduceR0
      period_start_date: 2020-01-31
      period_end_date: 2020-03-13   
      value:
        distribution: fixed
        value: 0
    Stopped:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0
    TestIsolate:
      template: ReduceR0
      period_start_date: 2020-03-19
      period_end_date: 2020-05-14
      value:
        distribution: fixed
        value: 0

seir:
  parameters:
    sigma: 1 / 5.2
    gamma:
      distribution: uniform
      low: 1 / 6
      high: 1 / 2.6
    R0s:
      distribution: uniform
      low: 2
      high: 3

hospitalization:
  paths:
    output_path: hospitalization
  parameters:
    time_hosp: [1.23, 0.79]
    time_disch: [log(11.5), log(1.22)]
    time_death: [log(11.25), log(1.15)]
    time_ICU: [log(8.25), log(2.2)]
    time_ICUdur: [log(16), log(2.96)]
    time_vent: [log(10.5), log((10.5-8)/1.35)]
    p_death: [.0025, .005, .01]
    p_death_names: ["low","med","high"]
    p_death_rate: 0.1
    p_ICU: 0.32
    p_vent: 0.15

report:
  data_settings:
    pop_year: 2018
  plot_settings:
    plot_intervention: TRUE
  formatting:
    scenario_labels_short: ["WH","UC"]
    scenario_labels:
      - Wuhan/Lockdown
      - Worst Case Uncontrolled
    scenario_colors: ["#D95F02", "#1B9E77"]
    pdeath_labels: ["0.25% IFR", "0.5% IFR", "1% IFR"]
    display_dates: ["2020-5-1", "2020-7-1", "2020-9-1"]
